version: '3.8'
services:
    db:
        image: mysql:8.0.31
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ../data/mysql/:/var/lib/mysql
    swift:
        image: dockerswiftaio/docker-swift:latest
        container_name: swift
        restart: unless-stopped
        ports:
            - "49000:8080"
        volumes:
            - ../data/swift/:/swift/nodes/1/node/sdb1
    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:8.5.3
        environment:
            - xpack.security.enabled=false
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
            - "9300:9300"
 
